export const sellerProductQueryKeys = {
  getSellerProductList: "getSellerProductList",
  getAutoGeneratedProductId: "getAutoGeneratedProductId",
  getProductInfo: "getProductInfo",
  saveSellerProductInfo: "saveSellerProductInfo",
  saveProductCertificatesInfo: "saveProductCertificatesInfo",
  saveProductLocationsInfo: "saveProductLocationsInfo",
  deleteProductLocationsInfo: "deleteProductLocationsInfo",
  saveProductWareHouseLocations: "saveProductWareHouseLocations",
  deleteProductWareHouseLocations: "deleteProductWareHouseLocations",
  saveProductPricingInfo: "saveProductPricingInfo",
  saveProductFileUpload: "saveProductFileUpload",
  saveProductFinal: "saveProductFinal",
  deleteProduct: "deleteProduct",
  activateProduct: "activateProduct",
  duplicateProduct: "duplicateProduct",
  productAction: "productAction",
  productFileUpload: "productFileUpload",
};

export const sellerQueryKeys = {
  getSellerOnboarding: "getSellerOnboarding",
  getSellerStatus: "getSellerStatus",
  getSellerOnboardingForAdmin: "getSellerOnboardingForAdmin",
  sellerOnboardingContactDetails: "sellerOnboardingContactDetails",
  sellerOnboardingGeneralInfo: "sellerOnboardingGeneralInfo",
  sellerFileUpload: "sellerFileUpload",
  sellerOnboardingProductDetails: "sellerOnboardingProductDetails",
  sellerOnboardingReachDetails: "sellerOnboardingReachDetails",
  sellerOnboardingCertificatehDetailsOne:
    "sellerOnboardingCertificatehDetailsOne",
  sellerOnboardingCompanyVerificationDocSave:
    "sellerOnboardingCompanyVerificationDocSave",
};
