import { paths } from "@/types/api-schema";
import { useMutation } from "@tanstack/react-query";
import {
  showErrorToastMessage,
  showSuccessToastMessage,
} from "@/utils/toast.utils";
import { sellerProductQueryKeys } from "@/constants/query-keys/seller.query-keys.constants";
import {
  activateProduct,
  deleteProduct,
  deleteProductLocation,
  deleteProductWarehouseLocation,
  duplicateProduct,
  getAutoGeneratedProductId,
  getSellerProductInfo,
  getSellerProductList,
  productAction,
  productFileUpload,
  saveProductCertificates,
  saveProductFileUpload,
  saveProductFinalInfo,
  saveProductInternInfo,
  saveProductLocation,
  saveProductOtherInfo,
  saveProductPricing,
  saveProductWarehouseLocation,
  saveSellerProductInfo,
} from "../api-functions/seller-product.api-functions.services";
import CustomError from "@/utils/CustomErrorClass";

export const UseGetSellerProductList = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.getSellerProductList],
    mutationFn: (
      query: paths["/v1/seller/product/list"]["get"]["parameters"]["query"],
    ) => getSellerProductList(query),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      // showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseGetProductId = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.getAutoGeneratedProductId],
    mutationFn: () => getAutoGeneratedProductId(),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      // showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseGetSellerProductInfo = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.getProductInfo],
    mutationFn: (
      id: paths["/v1/seller/product/get"]["get"]["parameters"]["query"]["id"],
    ) => getSellerProductInfo(id),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      // showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseSaveSellerProductInfo = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.saveSellerProductInfo],
    mutationFn: (
      data: paths["/v1/seller/product/product-info/save"]["post"]["requestBody"]["content"]["application/json"],
    ) => saveSellerProductInfo(data),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseSaveProductCertificates = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.saveProductCertificatesInfo],
    mutationFn: (values: {
      data: paths["/v1/seller/product/certificate-details/save"]["post"]["requestBody"]["content"]["application/json"];
      id: paths["/v1/seller/product/certificate-details/save"]["post"]["parameters"]["query"]["id"];
    }) => saveProductCertificates(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseSaveProductLocation = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.saveProductLocationsInfo],
    mutationFn: (values: {
      data: paths["/v1/seller/product/location/save"]["post"]["requestBody"]["content"]["application/json"];
      id: paths["/v1/seller/product/location/save"]["post"]["parameters"]["query"]["id"];
    }) => saveProductLocation(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseDeleteProductLocation = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.deleteProductLocationsInfo],
    mutationFn: (
      id: paths["/v1/seller/product/location/delete"]["delete"]["parameters"]["query"]["id"],
    ) => deleteProductLocation(id),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseSaveProductWarehouseLocation = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.saveProductWareHouseLocations],
    mutationFn: (values: {
      data: paths["/v1/seller/product/warehouse-location/save"]["post"]["requestBody"]["content"]["application/json"];
      id: paths["/v1/seller/product/warehouse-location/save"]["post"]["parameters"]["query"]["id"];
    }) => saveProductWarehouseLocation(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseDeleteProductWarehouseLocation = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.deleteProductWareHouseLocations],
    mutationFn: (
      id: paths["/v1/seller/product/warehouse-location/delete"]["delete"]["parameters"]["query"]["id"],
    ) => deleteProductWarehouseLocation(id),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseSaveProductPricingInfo = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.saveProductPricingInfo],
    mutationFn: (values: {
      data: paths["/v1/seller/product/pricing/save"]["post"]["requestBody"]["content"]["application/json"];
      id: paths["/v1/seller/product/pricing/save"]["post"]["parameters"]["query"]["id"];
    }) => saveProductPricing(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseSaveProductOtherInfo = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.saveProductPricingInfo],
    mutationFn: (values: {
      data: paths["/v1/seller/product/other/save"]["post"]["requestBody"]["content"]["application/json"];
      id: paths["/v1/seller/product/other/save"]["post"]["parameters"]["query"]["id"];
    }) => saveProductOtherInfo(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseSaveProductInternInfo = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.saveProductPricingInfo],
    mutationFn: (values: {
      data: paths["/v1/seller/product/intern/save"]["post"]["requestBody"]["content"]["application/json"];
      id: paths["/v1/seller/product/intern/save"]["post"]["parameters"]["query"]["id"];
    }) => saveProductInternInfo(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      // showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseSaveProductFileUpload = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.saveProductFileUpload],
    mutationFn: (values: {
      data: { file: File };
      type: paths["/v1/seller/product/file/upload"]["post"]["parameters"]["query"]["type"];
    }) => saveProductFileUpload(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseSaveProductFinalInfo = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.saveProductFinal],
    mutationFn: (values: {
      id: paths["/v1/seller/product/save"]["post"]["parameters"]["query"]["id"];
    }) => saveProductFinalInfo(values),
    onSuccess(data, variables, context) {
      successCallback(data);
      // showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseDeleteProduct = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.deleteProduct],
    mutationFn: (values: {
      id: paths["/v1/seller/product/delete"]["delete"]["parameters"]["query"]["id"];
    }) => deleteProduct(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseActivateProduct = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.activateProduct],
    mutationFn: (values: {
      id: paths["/v1/seller/product/active"]["put"]["parameters"]["query"]["id"];
    }) => activateProduct(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseDuplicateProduct = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.duplicateProduct],
    mutationFn: (values: {
      id: paths["/v1/seller/product/duplicate"]["put"]["parameters"]["query"]["id"];
    }) => duplicateProduct(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error, variables, context) {
      failureCallback();
      showErrorToastMessage(error?.message);
    },
  });
};

export const UseProductAction = (
  successCallback: (data: any) => void,
  failureCallback: (statusCode: string) => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.productAction],
    mutationFn: (
      values: paths["/v1/seller/product/action"]["put"]["parameters"]["query"],
    ) => productAction(values),
    onSuccess(data, variables, context) {
      successCallback(data.data);
      showSuccessToastMessage(data.message);
    },
    onError(error: CustomError, variables, context) {
      failureCallback(error.statusCode);
      showErrorToastMessage(error.message);
    },
  });
};

const errorMessages: string[] = [];

export const UseProductFileUpload = (
  successCallback: (data: any) => void,
  failureCallback: () => void,
) => {
  return useMutation({
    mutationKey: [sellerProductQueryKeys.productFileUpload],
    mutationFn: (values: {
      data: { file: File };
      type: paths["/v1/seller/product/file/upload"]["post"]["parameters"]["query"]["type"];
    }) => productFileUpload(values),
    onSuccess(data: any, variables, context) {
      successCallback(data);
    },
    onError(error, variables, context) {
      errorMessages.push(variables.data.file.name); // Store only the filename

      // Batch and display error messages after a delay
      setTimeout(() => {
        if (errorMessages.length) {
          showErrorToastMessage(
            `❌ Upload failed for: ${errorMessages.join(", ")}`,
          );
          errorMessages.length = 0; // Clear the queue
        }
      }, 3000);

      failureCallback();
    },
  });
};
