import client from "@/lib/fetch";
import { paths } from "@/types/api-schema";
import CustomError from "@/utils/CustomErrorClass";
import { getCookie } from "cookies-next";

interface Response {
  data?: any;
  error?: {
    message: string;
    code: string;
  };
}

export const getSellerProductList = async (
  query: paths["/v1/seller/product/list"]["get"]["parameters"]["query"],
) => {
  const response: Response = await client.GET("/v1/seller/product/list", {
    params: { query },
  });

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const getAutoGeneratedProductId = async () => {
  const response: Response = await client.GET(
    "/v1/seller/product/auto-generated-id",
  );

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const getSellerProductInfo = async (
  id: paths["/v1/seller/product/get"]["get"]["parameters"]["query"]["id"],
) => {
  const response: Response = await client.GET("/v1/seller/product/get", {
    params: { query: { id } },
  });

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const saveSellerProductInfo = async (
  data: paths["/v1/seller/product/product-info/save"]["post"]["requestBody"]["content"]["application/json"],
) => {
  const response: Response = await client.POST(
    "/v1/seller/product/product-info/save",
    {
      body: data,
    },
  );

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const saveProductCertificates = async ({
  data,
  id,
}: {
  data: paths["/v1/seller/product/certificate-details/save"]["post"]["requestBody"]["content"]["application/json"];
  id: paths["/v1/seller/product/certificate-details/save"]["post"]["parameters"]["query"]["id"];
}) => {
  const response: Response = await client.POST(
    "/v1/seller/product/certificate-details/save",
    {
      body: data,
      params: { query: { id } },
    },
  );

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const saveProductLocation = async ({
  data,
  id,
}: {
  data: paths["/v1/seller/product/location/save"]["post"]["requestBody"]["content"]["application/json"];
  id: paths["/v1/seller/product/location/save"]["post"]["parameters"]["query"]["id"];
}) => {
  const response: Response = await client.POST(
    "/v1/seller/product/location/save",
    {
      body: data,
      params: { query: { id } },
    },
  );

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const deleteProductLocation = async (
  id: paths["/v1/seller/product/location/delete"]["delete"]["parameters"]["query"]["id"],
) => {
  const response: Response = await client.DELETE(
    "/v1/seller/product/location/delete",
    {
      params: { query: { id } },
    },
  );

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const saveProductWarehouseLocation = async ({
  data,
  id,
}: {
  data: paths["/v1/seller/product/warehouse-location/save"]["post"]["requestBody"]["content"]["application/json"];
  id: paths["/v1/seller/product/warehouse-location/save"]["post"]["parameters"]["query"]["id"];
}) => {
  const response: Response = await client.POST(
    "/v1/seller/product/warehouse-location/save",
    {
      body: data,
      params: { query: { id } },
    },
  );

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const deleteProductWarehouseLocation = async (
  id: paths["/v1/seller/product/warehouse-location/delete"]["delete"]["parameters"]["query"]["id"],
) => {
  const response: Response = await client.DELETE(
    "/v1/seller/product/warehouse-location/delete",
    {
      params: { query: { id } },
    },
  );

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const saveProductPricing = async ({
  data,
  id,
}: {
  data: paths["/v1/seller/product/pricing/save"]["post"]["requestBody"]["content"]["application/json"];
  id: paths["/v1/seller/product/pricing/save"]["post"]["parameters"]["query"]["id"];
}) => {
  const response: Response = await client.POST(
    "/v1/seller/product/pricing/save",
    {
      body: data,
      params: { query: { id } },
    },
  );

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const saveProductOtherInfo = async ({
  data,
  id,
}: {
  data: paths["/v1/seller/product/other/save"]["post"]["requestBody"]["content"]["application/json"];
  id: paths["/v1/seller/product/other/save"]["post"]["parameters"]["query"]["id"];
}) => {
  const response: Response = await client.POST(
    "/v1/seller/product/other/save",
    {
      body: data,
      params: { query: { id } },
    },
  );

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const saveProductInternInfo = async ({
  data,
  id,
}: {
  data: paths["/v1/seller/product/intern/save"]["post"]["requestBody"]["content"]["application/json"];
  id: paths["/v1/seller/product/intern/save"]["post"]["parameters"]["query"]["id"];
}) => {
  const response: Response = await client.POST(
    "/v1/seller/product/intern/save",
    {
      body: data,
      params: { query: { id } },
    },
  );

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const saveProductFileUpload = async ({
  data,
  type,
}: {
  data: { file: File };
  type: paths["/v1/seller/product/file/upload"]["post"]["parameters"]["query"]["type"];
}) => {
  const authToken = getCookie("ACCESS_TOKEN");
  const formData = new FormData();
  formData.append("file", data.file);

  const myHeaders = new Headers();
  myHeaders.append("authorization", `Bearer ${authToken}`);

  let res = await fetch(
    `${process.env.NEXT_PUBLIC_API_BASE_URL}/v1/seller/product/file/upload?type=${type}`,
    {
      method: "POST",
      headers: myHeaders,
      body: formData,
      redirect: "follow",
    },
  );
  let response = await res.json();

  if (res.status !== 200) {
    throw new CustomError(response.message, response.code);
  }

  return response;
};

export const saveProductFinalInfo = async ({
  id,
}: {
  id: paths["/v1/seller/product/save"]["post"]["parameters"]["query"]["id"];
}) => {
  const response: Response = await client.POST("/v1/seller/product/save", {
    params: { query: { id } },
  });

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const deleteProduct = async ({
  id,
}: {
  id: paths["/v1/seller/product/delete"]["delete"]["parameters"]["query"]["id"];
}) => {
  const response: Response = await client.DELETE("/v1/seller/product/delete", {
    params: { query: { id } },
  });

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const activateProduct = async ({
  id,
}: {
  id: paths["/v1/seller/product/active"]["put"]["parameters"]["query"]["id"];
}) => {
  const response: Response = await client.PUT("/v1/seller/product/active", {
    params: { query: { id } },
  });

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const duplicateProduct = async ({
  id,
}: {
  id: paths["/v1/seller/product/duplicate"]["put"]["parameters"]["query"]["id"];
}) => {
  const response: Response = await client.PUT("/v1/seller/product/duplicate", {
    params: { query: { id } },
  });

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const productAction = async ({
  id,
  type,
}: {
  id: paths["/v1/seller/product/action"]["put"]["parameters"]["query"]["id"];
  type: paths["/v1/seller/product/action"]["put"]["parameters"]["query"]["type"];
}) => {
  const response: Response = await client.PUT("/v1/seller/product/action", {
    params: { query: { id, type } },
  });

  if (response.error) {
    throw new CustomError(response.error.message, response.error.code);
  }

  return response.data;
};

export const productFileUpload = async ({
  data,
  type,
}: {
  data: { file: File };
  type: paths["/v1/seller/product/file/upload"]["post"]["parameters"]["query"]["type"];
}) => {
  const authToken = getCookie("ACCESS_TOKEN");
  const formData = new FormData();
  formData.append("file", data.file);

  const myHeaders = new Headers();
  myHeaders.append("authorization", `Bearer ${authToken}`);

  let res = await fetch(
    `${process.env.NEXT_PUBLIC_API_BASE_URL}/v1/seller/product/file/upload?type=${type}`,
    {
      method: "POST",
      headers: myHeaders,
      body: formData,
      redirect: "follow",
    },
  );
  let response = await res.json();

  if (res.status !== 200) {
    throw new CustomError(response.message, response.code);
  }

  return response;
};
